server:
  port: 10001
  max-http-header-size: 20480
spring:
  application:
    name: member-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 4000 #断路器超时时间，默认1000ms
         # semaphore:
            # maxConcurrentRequests: 20  #当信号量隔离时   默认最大请求数为20
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
member:
    username: xyz
